grpc:
  events_options:
    grpc.enable_http_proxy: False
    grpc.max_send_message_length: 536870912
    grpc.max_receive_message_length: 536870912
    #grpc.keepalive_time_ms: 10000
    #grpc.keepalive_timeout_ms: 10000
    #grpc.permit_keepalive_without_calls: True
    #grpc.http2.min_ping_interval_without_data_ms: 1000
    #grpc.http2.max_pings_without_data: 0
    #grpc.http2.min_time_between_pings_ms: 1000
  processor_options:
    grpc.enable_http_proxy: False
    grpc.lb_policy_name: round_robin
    grpc.max_send_message_length: 536870912
    grpc.max_receive_message_length: 536870912
    #grpc.keepalive_time_ms: 10000
    #grpc.keepalive_timeout_ms: 10000
    #grpc.permit_keepalive_without_calls: True
    #grpc.http2.min_ping_interval_without_data_ms: 1000
    #grpc.http2.max_pings_without_data: 0
    #grpc.http2.min_time_between_pings_ms: 1000
